name: Release latest
on:
  push:
    branches: 
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
      with:
#         ref: someCustomTagName # You can change the name of the tag or branch with this input. Default: 'latest'

#         description: Description for the tag # Default: ''

        # Force-update a branch instead of using a tag.
        # Default: false
        force-branch: true
